ENV_FROM_APPLICATION_YML: "true"
BITLY_TOKEN: a998ad1a38cb580d09cc6789b3a3460c82e1c65c

development:
  DB_SCHEMA:             "backend_challenge_development"
  DB_PORT:               "32768"
  DB_USER_NAME:          "postgres"
  DB_PASSWORD:           "postgres"
  DB_HOST:               "localhost"

test:
  DB_SCHEMA:             "backend_challenge_test"
  DB_PORT:               "32768"
  DB_USER_NAME:          "postgres"
  DB_PASSWORD:           "postgres"
  DB_HOST:               "localhost"